# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET https://localhost:5001/api/ticketresponses?ticketNumber=1 HTTP/1.1
Accept: application/json

###

POST https://localhost:5001/api/ticketresponses HTTP/1.1
Accept: application/json
Content-Type: application/json

{"ticketNumber":2,"responseText":"een nieuw antwoord","isClientResponse":false}

###

PUT https://localhost:5001/api/tickets/3/State/Closed HTTP/1.1

###